#!/bin/bash
gcc-4.2 -arch i386 -c iosubs.c -o ../lib/iosubs.o
gfortran -O -ffixed-line-length-none -ffpe-trap= -o ../bin/hazFXnga7c hazFXnga7c.f ../lib/iosubs.o
gfortran -O -ffixed-line-length-none -ffpe-trap= -o ../bin/hazgridXnga3 hazgridXnga3.f ../lib/iosubs.o
